version: '2'
services:
  dspace:
    build: ./dspace/
    container_name: dspace
    ports:
      - '127.0.0.1:8080:80'
    environment:
      TZ: JST-9
    links:
      - dspacedb
  dspacedb:
    build: ./dspacedb/
    container_name: dspacedb
    environment:
      TZ: JST-9
    #
    #volumes:
    # - ~/mysql:/var/lib/mysql

